/* Auto-generated by Resources/precompute_assets.py. Do not edit by hand. */
#ifndef ASSETS_PRECOMPUTED_H
#define ASSETS_PRECOMPUTED_H

#define DIALOGUE_LAYOUT_dialogue_GunFound6 \
    .lineBreaks = {0, 21, 0, 0, 0}, \
    .textOrigins = {{8, 49}, {8, 55}, {0, 0}, {0, 0}, {0, 0}}, \
    .rectangleOrigin = {6, 47}, \
    .rectangleSize = {83, 15}

#define DIALOGUE_LAYOUT_dialogue_GunFound5 \
    .lineBreaks = {0, 18, 0, 0, 0}, \
    .textOrigins = {{14, 49}, {14, 55}, {0, 0}, {0, 0}, {0, 0}}, \
    .rectangleOrigin = {12, 47}, \
    .rectangleSize = {71, 15}

#define DIALOGUE_LAYOUT_dialogue_GunFound4 \
    .lineBreaks = {0, 0, 0, 0, 0}, \
    .textOrigins = {{44, 55}, {0, 0}, {0, 0}, {0, 0}, {0, 0}}, \
    .rectangleOrigin = {42, 53}, \
    .rectangleSize = {11, 9}

#define DIALOGUE_LAYOUT_dialogue_GunFound3 \
    .lineBreaks = {0, 19, 0, 0, 0}, \
    .textOrigins = {{12, 49}, {12, 55}, {0, 0}, {0, 0}, {0, 0}}, \
    .rectangleOrigin = {10, 47}, \
    .rectangleSize = {75, 15}

#define DIALOGUE_LAYOUT_dialogue_GunFound2 \
    .lineBreaks = {0, 19, 0, 0, 0}, \
    .textOrigins = {{12, 49}, {12, 55}, {0, 0}, {0, 0}, {0, 0}}, \
    .rectangleOrigin = {10, 47}, \
    .rectangleSize = {75, 15}

#define DIALOGUE_LAYOUT_dialogue_GunFound1 \
    .lineBreaks = {0, 0, 0, 0, 0}, \
    .textOrigins = {{34, 55}, {0, 0}, {0, 0}, {0, 0}, {0, 0}}, \
    .rectangleOrigin = {32, 53}, \
    .rectangleSize = {31, 9}

#define DIALOGUE_LAYOUT_dialogue_KnifeFound1 \
    .lineBreaks = {0, 20, 0, 0, 0}, \
    .textOrigins = {{10, 49}, {10, 55}, {0, 0}, {0, 0}, {0, 0}}, \
    .rectangleOrigin = {8, 47}, \
    .rectangleSize = {79, 15}

#define DIALOGUE_LAYOUT_dialogue_KnifeFoundAgain1 \
    .lineBreaks = {0, 20, 0, 0, 0}, \
    .textOrigins = {{10, 49}, {10, 55}, {0, 0}, {0, 0}, {0, 0}}, \
    .rectangleOrigin = {8, 47}, \
    .rectangleSize = {79, 15}

#define DIALOGUE_LAYOUT_dialogue_Healed2 \
    .lineBreaks = {0, 0, 0, 0, 0}, \
    .textOrigins = {{34, 55}, {0, 0}, {0, 0}, {0, 0}, {0, 0}}, \
    .rectangleOrigin = {32, 53}, \
    .rectangleSize = {31, 9}

#define DIALOGUE_LAYOUT_dialogue_Healed1 \
    .lineBreaks = {0, 0, 0, 0, 0}, \
    .textOrigins = {{12, 55}, {0, 0}, {0, 0}, {0, 0}, {0, 0}}, \
    .rectangleOrigin = {10, 53}, \
    .rectangleSize = {75, 9}

#define DIALOGUE_LAYOUT_dialogue_Injured2 \
    .lineBreaks = {0, 0, 0, 0, 0}, \
    .textOrigins = {{38, 55}, {0, 0}, {0, 0}, {0, 0}, {0, 0}}, \
    .rectangleOrigin = {36, 53}, \
    .rectangleSize = {23, 9}

#define DIALOGUE_LAYOUT_dialogue_Injured \
    .lineBreaks = {0, 0, 0, 0, 0}, \
    .textOrigins = {{40, 55}, {0, 0}, {0, 0}, {0, 0}, {0, 0}}, \
    .rectangleOrigin = {38, 53}, \
    .rectangleSize = {19, 9}

#define DIALOGUE_LAYOUT_dialogue_Room2 \
    .lineBreaks = {0, 21, 0, 0, 0}, \
    .textOrigins = {{8, 49}, {8, 55}, {0, 0}, {0, 0}, {0, 0}}, \
    .rectangleOrigin = {6, 47}, \
    .rectangleSize = {83, 15}

#define DIALOGUE_LAYOUT_dialogue_Room1 \
    .lineBreaks = {0, 0, 0, 0, 0}, \
    .textOrigins = {{38, 55}, {0, 0}, {0, 0}, {0, 0}, {0, 0}}, \
    .rectangleOrigin = {36, 53}, \
    .rectangleSize = {23, 9}

#define MAP_SPAWN_SmallMap \
    .DefaultSpwanPoint = {13, 5}

#define MAP_SPAWN_BigMap \
    .DefaultSpwanPoint = {26, 20}

#define MAP_SPAWN_TestMap \
    .DefaultSpwanPoint = {13, 15}

#define MAP_SPAWN_AgentOrangeMap \
    .DefaultSpwanPoint = {15, 20}

#define MAP_SPAWN_WallDemoMap \
    .DefaultSpwanPoint = {7, 6}

#endif
